# # This workflow will install Python dependencies, run tests and lint with a single version of Python
# # For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build-docker

on:
  workflow_run:
    workflows:
      - python-testing
    branches:
      - main
      - develop
    types:
      - completed

jobs:
  docker-build:

    runs-on: [SI, standard]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    # - name: Docker Login
#       uses: docker/login-action@v1.10.0
#       with:
#         registry: harbor.gradiant.org/si-medeva-pr-01432
#         username: ${{ secrets.HarborUser }}
#         password: ${{ secrets.HarborPass }}
#         # Log out from the Docker registry at the end of a job
#         logout: true
    
#     - name: Extract Branch name
#       run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

#     - name: Build image
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         file: Dockerfile
#         push: true
#         tags: harbor.gradiant.org/si-medeva-pr-01432/SchemaMatchingModule:${{ env.BRANCH }}
#         build-args: |
#           BRANCH=${{ env.BRANCH }}